### ISSUE TITLE
Accelerometer

### ISSUE THREAD

**Issue by JpEncausse** [sandeepmistry/node-bleacon#18]
Did you find a way to retrieve accelerometer data ? It seems there is an update few month ago ? 
According to their forum accelerometer only tells moving or not.

**Comment by sandeepmistry** [comment]
@JpEncausse https://github.com/sandeepmistry/node-bleacon/commit/1e3526956501f6253147efd76e2455336d7cd923 adds some API's for motion ...

**Comment by morganzysman** [comment]
According to the last post it is then possible to read this data. 
Regards
