### ISSUE TITLE
Scanning mor than one uuid

### ISSUE THREAD

**Issue by PowerPan** [sandeepmistry/node-bleacon#22]
Hey,

it is possible to scan for multiple defined uuid's at the same time? Or can i only scan for all and for one uuid ?

thx

**Comment by sandeepmistry** [comment]
@PowerPan great question!

Currently all or one uuid at a time. Although it could be changed, see:

https://github.com/sandeepmistry/node-bleacon/blob/master/lib/bleacon.js#L46

https://github.com/sandeepmistry/node-bleacon/blob/master/lib/bleacon.js#L85

If an array was used to store the startScanning params from each call. Pull request would be great if you have time to make the mods.
