### ISSUE TITLE
Bleacon.StartAdvertising help needed! (raspberry emulating iBeacon)

### ISSUE THREAD

**Issue by sleeperagent** [sandeepmistry/node-bleacon#28]
Hi!

I'm trying to build something that emulates an iBeacon on a raspberry PI using node-bleacon.

Using `Bleacon.StartAdvertising()` I can get the raspberry's usb dongle to activate the BLE radio. It shows up in BLE Scanner and LightBlue scanner (IOS). But when interrogating the device more closely there is no "advertisement" UUID (ie. the ibeacon uuid) present. It will not show up in the Estimote ios app for example...

What am I doing wrong / missing here?

**Comment by sleeperagent** [comment]
Do the advertising uuids vary by region? I'm in Finland. I solved this issue using the uuid b9407f30f5f8466eaff925556b57fe6d instead of the one mentioned in the documentation for Bleacon. Now the raspberry pi running bleacon shows up as an ibeacon in the estimote app.

**Comment by sandeepmistry** [comment]
@sleeperagent this is excepted behaviour, the Estimote app only scans for Estimote hardware. LightBlue doesn't display manufacturer data.

I suggest you use a generic iBeacon tool in, for example https://itunes.apple.com/ca/app/locate-beacon/id738709014?mt=8 - it will allow you to select a UUID to range or monitor.
