### ISSUE TITLE
Beacons no longer detected on El Capitan

### ISSUE THREAD

**Issue by buffpojken** [sandeepmistry/node-bleacon#31]
A script using bleacon working perfectly no longer works on El Capitan GM. 

When running the following
```
Bleacon.on('discover', function(bleacon){
  console.log("monkey");
  console.log(bleacon.uuid);
});
Bleacon.startScanning("3ddd37e386d1487e9f4aba1dbf64d274");
```
nothing is detected on OS X El Capitan, while the exact same script (verified via git) on a raspberry detects the correct iBeacon immediately. 

The script worked fine on Yosemite and Maverick.

**Comment by sandeepmistry** [comment]
@buffpojken can you please provide debug logs?

```DEBUG=* node <file>.js```

**Comment by buffpojken** [comment]
Absolutely, see below: 

```nightgaunt:ghostbox-node buffpojken$ DEBUG=* node server.js 
  yosemite-bindings sendCBMsg: 1, {
  "kCBMsgArgName": "node-1443540811626",
  "kCBMsgArgOptions": {
    "kCBInitOptionShowPowerAlert": 0
  },
  "kCBMsgArgType": 0
} +0ms
  bleacon startScanning: uuid = 3ddd37e386d1487e9f4aba1dbf64d274, major = undefined, minor = undefined +114ms
sanning
  yosemite-bindings xpcEvent: {
  "kCBMsgId": 6,
  "kCBMsgArgs": {
    "kCBMsgArgState": 5
  }
} +2ms
  yosemite-bindings state change poweredOn +0ms
  noble stateChange poweredOn +0ms
  yosemite-bindings sendCBMsg: 29, {
  "kCBMsgArgOptions": {
    "kCBScanOptionAllowDuplicates": 1
  },
  "kCBMsgArgUUIDs": []
} +0ms
  noble scanStart +0ms
  bleno addressChange b8:e8:56:41:52:05 +140ms
  bindings sendCBMsg: 1, {
  "kCBMsgArgName": "node-1443540811883",
  "kCBMsgArgOptions": {
    "kCBInitOptionShowPowerAlert": 1
  },
  "kCBMsgArgType": 1
} +0ms
  bindings xpcEvent: {
  "kCBMsgId": 6,
  "kCBMsgArgs": {
    "kCBMsgArgState": 5
  }
} +1ms
  bindings state change poweredOn +0ms
  bleno stateChange poweredOn +0ms
```

**Comment by sandeepmistry** [comment]
@buffpojken sees ok on my El Capitan Mac running: 10.11 (15A282b)

What version are you running? Have you tried killing blued? Also, can you please check if the OS X version of the LightBlue app can see them.

**Comment by buffpojken** [comment]
Okey, this is weird. 

Running the same version of El Capitan. 

Running node-bleacon 0.4.0 backed by bleano 0.3.0. The LightBlue-app on OS X detects nothing, the LightBlue-app on iPhone works just fine. Still nothing being passed on bleacon, but I'm starting to guess it's my hardware acting up.

**Comment by sandeepmistry** [comment]
@buffpojken hmm, what if you use LightBlue on iOS to create a BLE peripheral? Can your Mac see it?

You could try clearing the CoreBluetooth cache on OS X: http://stackoverflow.com/a/23573314/2020087

**Comment by buffpojken** [comment]
Nope, even a virtual BLE peripheral from the iOS app is not detected by LightBlue on the mac. 

Clearing the CoreBluetooth cache didn't change anything either. 

The mystery continues. But I feel it's fairly certain it's not a bug in bleacon anyhow :)

**Comment by buffpojken** [comment]
@sandeepmistry Can I ask how you verified it works fine on your El Capitan?

**Comment by sandeepmistry** [comment]
@buffpojken 

1. ```npm install bleacon```
1. ```node node_modules/bleacon/test.js```
1. On iOS, run virtual beacon on Estimote app

**Comment by sandeepmistry** [comment]
@buffpojken could you try this: http://stackoverflow.com/a/23573314/2020087

@pide2000 was also having the same issue, see their comment here: https://github.com/sandeepmistry/noble/issues/267#issuecomment-158196597

**Comment by sandeepmistry** [comment]
Closing, as it's probably related to the CoreBluetooth plist files. Please re-open if this does not fix the issue for you.

**Comment by buffpojken** [comment]
Sorry for the delay in checking this, but unfortunately this doesn't change anything of the above.

**Comment by sandeepmistry** [comment]
@buffpojken fair enough, I'm out of ideas on what you can try next. Seems like an OS or hardware issue.

**Comment by buffpojken** [comment]
That makes two of us - I'm out of ideas as well, but think it's an OS issue since the code worked just fine before installing El Capitan. 

Thanks anyway!

**Comment by mllanes** [comment]
for what is worth, I'm having the same issue with High Sierra
