### ISSUE TITLE
beacon communication between 2 galileo

### ISSUE THREAD

**Issue by rabertol** [sandeepmistry/node-bleacon#32]
Hi i am trying to connect two galileos using beacon but discover and adverting dont fing ench other... how can i use to communicate beetwhenn galileos? this is my code in both galileos:

var Bleacon = require('bleacon');
console.log("START");

var uuid = 'e2c56db5dffb48d2b060d0f5a71096e6';
var major = 0; // 0 - 65535
var minor = 0; // 0 - 65535
var measuredPower = -59; // -128 - 127 (measured RSSI at 1 meter)

Bleacon.startScanning();
console.log("start scaning");
//Bleacon.startScanning('e2c56db5dffb48d2b060d0f5a71096e0', 0, 0);
console.log("start adverting");
Bleacon.startAdvertising(uuid, major, minor, measuredPower);
Bleacon.on('discover', function (bleacon) {
    console.log("discover");
    console.log(bleacon);
});

**Comment by sandeepmistry** [comment]
@rabertol please provide debug output: ```sudo DEBUG=* node <file>.js```

Also, do things work if you have one galileo scanning and the other one advertising?

**Comment by sandeepmistry** [comment]
Closing do to inactivity, please re-open with requested info.
