### ISSUE TITLE
Estimote.discoverAll() leaks and misses discovering devices

### ISSUE THREAD

**Issue by eric1138** [sandeepmistry/node-bleacon#34]
Estimote.discoverAll () leaks as it repeatedly discovers the same devices over and over again. Setting SCANDUPLICATES to false causes it to miss when a device goes out of range and returns. 

Would be more useful if it returned an array of all currently visible estimote devices as some of the other noble functions do.

**Comment by sandeepmistry** [comment]
The leak is solved upstream by https://github.com/sandeepmistry/noble-device/pull/22.
