### ISSUE TITLE
Gigaset G-Tag can't be found

### ISSUE THREAD

**Issue by antonkluev** [sandeepmistry/node-bleacon#36]
Hi,

ive bought the Gigaset G-Tag and it is invisible for Bleacon.. ive tested 

1. Bleacon on Raspberry (as receiver) with my iPhone (as tranceiver) 
2. G-Tag (as tranceiver) with iPhone (as receiver) 
3. G-Tag (as tranceiver) with LightBlue from MacAppStore (as receiver) (it shows also the RSSI correctly)
and everything works!

until i try to find G-Tag (tranceiver) on my raspberry (receiver)...
where is the issue?

**Comment by sandeepmistry** [comment]
@antonkluev 

There is no mention of the iBeacon on the [Gigaset G-Tag website](http://www.gigaset-elements.com/en/19-showcase/bluetooth-beacon/26-gigaset-g-tag-en.html).

I suggest you try the noble [advertisement-discovery.js example](https://github.com/sandeepmistry/noble/blob/master/examples/advertisement-discovery.js) to set what the peripheral actually advertises.
