### ISSUE TITLE
unable to run bleacon on Intel edison

### ISSUE THREAD

**Issue by krishnatgkk1** [sandeepmistry/node-bleacon#37]
When i run the my node application on Intel edison it throws me error Cannot find module 'bluetooth-hci-socket'  . Let me know if I am missing something. I was able to use this on my local system .

I am trying to scan estomote stickers from Intel edison. please let me know if I can use any other library too.

Thanks
Krishna

**Comment by sandeepmistry** [comment]
@krishnatgkk1 what is the output of ```npm install bluetooth-hci-socket```?

**Comment by krishnatgkk1** [comment]
Here is the output.

I am not from Linux background. Can you please help me on this.

The Objective of my Project is Intel edison to scan nearby estimote
stickers and report out if any sticker is moving or not.

Let me know if more details are required.

root@edison
:~# npm install bluetooth-hci-socket -g
-
> usb@1.1.1
 install /usr/lib/node_modules/bluetooth-hci-socket/node_modules/usb
> node-pre-gyp install --fallback-to-build

make: Entering directory
'/usr/lib/node_modules/bluetooth-hci-socket/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No
such file or directory
 #include <libudev.h>
                     ^
compilation terminated.
libusb.target.mk:124
: recipe for target
'Release/obj.target/libusb/libusb/libusb/os/linux_udev.o' failed
make: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o]
Error 1
make: Leaving directory
'/usr/lib/node_modules/bluetooth-hci-socket/node_modules/usb/build'
gyp ERR! build error

gyp ERR! stack
 Error: `make` failed with exit code: 2
gyp ERR! stack
     at ChildProcess.onExit
(/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack
     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack
     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System
 Linux 3.10.17-poky-edison+
gyp ERR! command
 "/usr/bin/node"
"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"build" "--fallback-to-build"
"--module=/usr/lib/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding/usb_bind
ings.node" "--module_name=usb_bindings"
"--module_path=/usr/lib/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding"
gyp ERR! cwd /usr/lib/node_modules/bluetooth-hci-socket/node_modules/usb





Thanks
Krishna
(937)-369-4598

**Comment by sandeepmistry** [comment]
@krishnatgkk1 please see https://communities.intel.com/thread/55789?start=0&tstart=0

You need to have ```libudev-dev``` installed.
