### ISSUE TITLE
discoverAll() don't show Estimotes

### ISSUE THREAD

**Issue by hlsmtgo** [sandeepmistry/node-bleacon#39]
Hello,

I'm working with a Rapsberry Pi 3 trying to connect with the Estimotes, but when I use the discoverAll() function they don't appear on the command line. Using the bluetoothctl scan they are detected.

The code is the following: 
`var Estimote = require('bleacon').Estimote;

Estimote.discoverAll(function (estimote) {
  console.log(JSON.stringfy(estimote));
});`

Is something wrong with the code?

Regards,

**Comment by sandeepmistry** [comment]
@hlsmtgo what firmware is the beacon running? Newer firmware versions are probably not supported.

Please provide debug output: ```DEBUG=* node <file>.js```

**Comment by hlsmtgo** [comment]
` hci onSocketData: 043e2b0201030134d1c5a671ee1f02010403030f1817ff5d010197cf2133beb9b1ae04829a2135fdfdc1a00167bc +499ms
  hci   event type = 4 +0ms
  hci   sub event type = 62 +0ms
  hci           LE meta event type = 2 +0ms
  hci           LE meta event status = 1 +0ms
  hci           LE meta event data = 030134d1c5a671ee1f02010403030f1817ff5d010197cf2133beb9b1ae04829a2135fdfdc1a00167bc +0ms
  hci onSocketData: 043e2b0201030134d1c5a671ee1f02010403030f1817ff5d010197cf2133beb9b1ae04829a2135fdfdc1a00167bc +0ms
  hci   event type = 4 +1ms
  hci   sub event type = 62 +0ms
  hci           LE meta event type = 2 +0ms
  hci           LE meta event status = 1 +0ms
  hci           LE meta event data = 030134d1c5a671ee1f02010403030f1817ff5d010197cf2133beb9b1ae04829a2135fdfdc1a00167bc +0ms
  hci                   type = 3 +0ms
  hci                   address = ee:71:a6:c5:d1:34 +0ms
  hci                   address type = random +0ms
  hci                   eir = 02010403030f1817ff5d010197cf2133beb9b1ae04829a2135fdfdc1a00167 +0ms
  hci                   rssi = -68 +0ms
  gap advertisement = {"manufacturerData":{"type":"Buffer","data":[93,1,1,151,207,33,51,190,185,177,174,4,130,154,33,53,253,253,193,160,1,103]},"serviceData":[],"serviceUuids":["180f"]} +0ms
  hci onSocketData: 043e2b02010301d7d1a52f3ec81f02010403030f1817ff5d0101692a7d499564e291048299b135fcfdbf8d0057bc +170ms
  hci   event type = 4 +0ms
  hci   sub event type = 62 +0ms
  hci           LE meta event type = 2 +0ms
  hci           LE meta event status = 1 +0ms
  hci           LE meta event data = 0301d7d1a52f3ec81f02010403030f1817ff5d0101692a7d499564e291048299b135fcfdbf8d0057bc +0ms
  hci onSocketData: 043e2b02010301d7d1a52f3ec81f02010403030f1817ff5d0101692a7d499564e291048299b135fcfdbf8d0057bc +0ms
  hci   event type = 4 +1ms
  hci   sub event type = 62 +0ms
  hci           LE meta event type = 2 +0ms
  hci           LE meta event status = 1 +0ms
  hci           LE meta event data = 0301d7d1a52f3ec81f02010403030f1817ff5d0101692a7d499564e291048299b135fcfdbf8d0057bc +0ms
  hci                   type = 3 +0ms
  hci                   address = c8:3e:2f:a5:d1:d7 +0ms
  hci                   address type = random +0ms
  hci                   eir = 02010403030f1817ff5d0101692a7d499564e291048299b135fcfdbf8d0057 +0ms
  hci                   rssi = -68 +0ms
  gap advertisement = {"manufacturerData":{"type":"Buffer","data":[93,1,1,105,42,125,73,149,100,226,145,4,130,153,177,53,252,253,191,141,0,87]},"serviceData":[],"serviceUuids":["180f"]} +0ms
  hci set scan enabled - writing: 010c20020001 +439ms
  hci set advertise enable - writing: 010a200100 +1ms
`

that's the output when i run the command

**Comment by sandeepmistry** [comment]
@hlsmtgo it looks like you are using a Estimote sticker, please use: https://github.com/sandeepmistry/node-bleacon/tree/master/estimote-sticker
