### ISSUE TITLE
Estimote sticker movement

### ISSUE THREAD

**Issue by skrichten** [sandeepmistry/node-bleacon#40]
I noticed that the regular estimote has a way to subscribe to motion changes ...

`estimote.subscribeMotion(callback(error));`

I tried to use this with the estimote stickers, but that didn't work.  I expected this since I noticed there is separate code for estimote stickers.  That code however does not include any way to subscribe to motion events.  Is there a way to do this with estimote stickers?

**Comment by sandeepmistry** [comment]
@skrichten there's no need to connect to the beacon. Motion data is advertised (at least with the old stickers I had).

See: https://github.com/sandeepmistry/node-bleacon/blob/master/estimote-sticker/estimote-sticker.js#L103-L107

Try out the test.js for estimote-stciker.
