### ISSUE TITLE
Retrieving Major ID from Stickers

### ISSUE THREAD

**Issue by ChrisHayduk** [sandeepmistry/node-bleacon#41]
I have been looking through the library's code for stickers, and it does not seem like there is a way to get the major ID for a sticker. Is this currently possible with the existing code?

Thanks!

**Comment by sandeepmistry** [comment]
@ChrisHayduk stickers do not broadcast majors (at least the older ones I tried).

The following info is broadcasted: https://github.com/sandeepmistry/node-bleacon/blob/master/estimote-sticker/estimote-sticker.js#L115-L129

From what I remember, I think the Estimote SDK looks up the ```id``` value with their cloud service to determine the "major".
