### ISSUE TITLE
More than one Bluetooth dongle

### ISSUE THREAD

**Issue by matboehmer** [sandeepmistry/node-bleacon#44]
Is it possible to use this library in combination with mode than one Bluetooth dongles, i.e. more than one Bluetooth radios? For instance, I would like to connect to USB Bluetooth dongles to a Raspberry Pi an then know which of those two receives what kind of beacon data.

**Comment by sandeepmistry** [comment]
@matboehmer please see: https://github.com/sandeepmistry/noble#multiple-adapters

Right now you'll need a node process per adapter.
