### ISSUE TITLE
Estimote Sticker Major/Minor

### ISSUE THREAD

**Issue by fenwick67** [sandeepmistry/node-bleacon#46]
Looking at results for `Bleacon.EstimoteSticker discover` events and comparing to the Estimote app, what Estimote calls the Major and Minor on stickers is the last 4 bytes of the UUID returned by `node-bleacon` converted to decimal.

Ex: 

Estimote app:
uuid:`abababab-cdcd-efef-0101-232323232323`
major:`17733`
minor:`26471`

`node-bleacon.EstimoteSticker`: 
uuid:`ababababcdcdefef010123232323232345456767`

Also when using the evothings library (on Android anyway), it calls these last bytes the major and minor too.  So it might be smart to break this out into major and minor (or have an option for it).

Also see #41

**Comment by sandeepmistry** [comment]
@fenwick67 thanks for the info.

Can you submit a PR for this change? Unfortunately the stickers I have all have dead batteries, so I can't test.

**Comment by danibram** [comment]
Hi guys @sandeepmistry @fenwick67
I tested it with my stickers.
I added this in the PR #53 
Thanks!

**Comment by sandeepmistry** [comment]
Closing, since @danibram has done this in #53 :)
