### ISSUE TITLE
estimote-sticker real time

### ISSUE THREAD

**Issue by morganzysman** [sandeepmistry/node-bleacon#48]
Hello every one,

I was wondering if it is poiible to connect to the sticker (like the estimote APP does) and have the readings in real time.

In the estimote app it is pretty insane how fast the motion values are being updated.

If any one has tried it, what is the battery impact?

Thank you in advance,

Regards ,

Morgan

**Comment by sandeepmistry** [comment]
@morganzysman from my understanding, the sticker is not connectable. All motion events are just broadcasted.
