### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by jonathanwiesel** [sandeepmistry/node-bleacon#5]
Any idea if this can be implemented in a Node.js environment inside a Raspberry Pi?

**Comment by brianormous** [comment]
I'm a little new to this stuff...on a raspberry pi 2 B with Raspian and BLE usb, i'm running node and nodejs versions v4.4.5 and v.0.12.13...i've install the prereqs...when I try to run Bleacon, I keep getting "ERROR: Module version mismatch. Expected 46, got 14...". did anyone else run into this issue? any suggestions how to fix or diagnose?

**Comment by sandeepmistry** [comment]
@brianormous I suggest you do a clean install of `node-bleacon`. The version mismatch means that you ran `npm install` with an older version of Node.js and are trying to run it with a newer version.

Please see http://stackoverflow.com/a/15584530/2020087 for more info.
