### ISSUE TITLE
bluetooth-hci-socket 8.6 megabytes

### ISSUE THREAD

**Issue by benjaminhon** [sandeepmistry/node-bleacon#58]
Hi previously, bluetooth-hci-socket was about only half a megabyte. Now it is 8.6 megabytes, since both bleno and noble depends on it then bleacon package is now 33 megabytes!

i think it still works previously, without being so bloated, any advice on this?

thanks

**Comment by sandeepmistry** [comment]
@benjaminhon why the concern about size? Have you looked into which folders or dependencies added size?

**Comment by benjaminhon** [comment]
The largest folder in bluetooth-hci-socket seems to be usb which is 8 mb

**Comment by sandeepmistry** [comment]
You can safely delete it, it's an optional dependency on Linux, just needed for Windows.

**Comment by sandeepmistry** [comment]
Closing this for now unless there is something else to discuss.
