### ISSUE TITLE
estimote-sticker not sending rssi in latest npm build

### ISSUE THREAD

**Issue by mheiber** [sandeepmistry/node-bleacon#59]
payload is like this:

```json
{
  "id": "9ca626b86a3a5c26",
  "uuid": "d0d3fa86ca7645ec9bd96af49ca626b86a3a5c26",
  "type": "SB0",
  "firmware": "unknown",
  "bootloader": "SB1.0.0",
  "temperature": 23.8125,
  "moving": false,
  "batteryLevel": "unknown",
  "acceleration": {
    "x": -15.625,
    "y": 46.875,
    "z": -1000
  },
  "currentMotionStateDuration": 1560,
  "previousMotionStateDuration": 0,
  "power": 7,
  "firmwareState": "app"
}
```

Based on the docs (and the purpose of beacons), we're expecting to receive the rssi so we can calculate approximate distance. I'll PR a patch for this soon.

The problem is that `rssi` is not added to the `sticker` object in `estimote-sticker.js` in the version of the library that is on npm, even though the code in the repo is correct. Can you publish a patch to npm?

**Comment by sandeepmistry** [comment]
> Can you publish a patch to npm?

Done, v0.5.0 published to npm.
