### ISSUE TITLE
Read uuid, minor and major with EstimoteSticker

### ISSUE THREAD

**Issue by mathil** [sandeepmistry/node-bleacon#62]
Hi. I have a problem with read uuid, minor and major with estimote-sticker.js. I can change it in android estimote app but node.js application always return values before modified. Can somebody help me with this?

**Comment by sandeepmistry** [comment]
Unfortunately I don't have any working stickers any more. Does the Android app show the new values when scanning as well?

Maybe the app is translating the old values to new locally or in the cloud?

**Comment by mathil** [comment]
This is my mistake. Beacon stickers uses nearable protocol that uses the ID and type instead of UUID, minor and major. And these values can not be modified in nearable protocol. Sorry for the confusion.

**Comment by Bengel15** [comment]
@sandeepmistry Why don't you have any working stickers left? Did the Battery die? You could change the  Battery. Just cut them open. The have a Standard coin cell. 
![img_20160719_145614](https://cloud.githubusercontent.com/assets/4389929/18304492/f20a53a2-74e2-11e6-998a-8ab93156baae.jpg)

**Comment by sandeepmistry** [comment]
@mathil ok, thanks for the update - I'll close

@Bengel15 I tried opening the two 1st gen stickers I had, unfortunately I wasn't gentle enough and ripped the PCB.
