### ISSUE TITLE
no compatible version found: bleno@^0.5.0

### ISSUE THREAD

**Issue by neosource** [sandeepmistry/node-bleacon#64]
when doing an npm install for bleacon the following error is generated

> xpc-connection@0.1.4 install /Users/ravi/code/BeaconDetect/node_modules/xpc-connection
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/XpcConnection.o
  SOLINK_MODULE(target) Release/binding.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
BeaconDetect@1.0.0 /Users/ravi/code/BeaconDetect
└─┬ bleno@0.4.1
  └─┬ xpc-connection@0.1.4 
    └── nan@2.4.0 

npm WARN optional Skipping failed optional dependency /bleno/bluetooth-hci-socket:
npm WARN notsup Not compatible with your operating system or architecture: bluetooth-hci-socket@0.5.1
npm WARN optional Skipping failed optional dependency /noble/bluetooth-hci-socket:
npm WARN notsup Not compatible with your operating system or architecture: bluetooth-hci-socket@0.5.1
npm WARN BeaconDetect@1.0.0 No description
npm WARN BeaconDetect@1.0.0 No repository field.
npm WARN BeaconDetect@1.0.0 No license field.
redbook:BeaconDetect ravi$ sudo npm install
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! No compatible version found: bleno@^0.5.0
npm ERR! Valid install targets:
npm ERR! 0.4.1, 0.4.0, 0.3.5, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.1, 0.2.0, 0.1.14, 0.1.13, 0.1.12, 0.1.11, 0.1.10, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0, 0.0.3, 0.0.2, 0.0.1
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ravi/code/BeaconDetect/npm-debug.log
redbook:BeaconDetect ravi$

**Comment by neosource** [comment]
Looks like something to do with bleacon package. Getting the same error when I do $ npm install bleacon

**Comment by sandeepmistry** [comment]
Hi @neosource,

I've correct this and published v0.5.1 to npm. package.json had an incorrect value for bleno (0.5.0), the latest is 0.4.1.
