### ISSUE TITLE
Beacon is disconnecting after connecting with in few seconds

### ISSUE THREAD

**Issue by panchalneel** [sandeepmistry/node-bleacon#66]
Below i am attaching my sample code..

List of problems 

1) estimote.on('disconnect') method is calling after few seconds (after approx 9 seconds)
2) Not getting proper Temprature
3) motionStateChange method is not called properly so unable to get beacon is moving or not

Note : my firmware version is A3.2.0

var Estimote = require('bleacon').Estimote;
Estimote.discoverAll(function (estimote) {
    
    estimote.connectAndSetUp(function (connectError) {
        if (!connectError) {
            estimote.readDeviceName(function (error, deviceName) {
                if (error) {
                    console.log('Error occur while getting device name, Error : ' + error);
                } else {
                    console.log("Device Name :" + estimote);
                }
            });

            estimote.readTemperature(function (error, temprature) {
                console.log("Temprature :" + temprature);
            });

            estimote.on('motionStateChange', function (isMoving) {
                console.log("Is Beacon Moving  :" + isMoving);
            });
            estimote.subscribeMotion(function (error) {
                if (error) {
                    console.log("Error While Subscriing motion code");
                }
            });

            estimote.on('disconnect', function() {
                console.log('disconnected!');
            });
        }
    });
});

**Comment by sandeepmistry** [comment]
This is the same issue as https://github.com/sandeepmistry/node-bleacon/issues/65#issuecomment-248772594.

I'm closing this as a duplicate.

**Comment by panchalneel** [comment]
@sandeepmistry Beacon is disconnecting after few seconds is it issue of firmware??

**Comment by sandeepmistry** [comment]
@panchalneel newer f/w is not compatible with this module. I've added a note in https://github.com/sandeepmistry/node-bleacon/commit/5dad64d8fe3dab6fe0e2641cc98fcaa47a82f5d2.
