### ISSUE TITLE
Installation on C.H.I.P. mini pc

### ISSUE THREAD

**Issue by dev-prairedogtech** [sandeepmistry/node-bleacon#69]
We just got a C.H.I.P. mini pc by Next Thing Co and we are trying to install bleacon just like we do under Raspbian OS on a Raspberry Pi, but it just doesn’t want to install?  

Using - sudo npm install bleacon

![img_0070](https://cloud.githubusercontent.com/assets/23701790/20578363/00f3a118-b195-11e6-858c-8f15efff7e74.JPG)

**Comment by sandeepmistry** [comment]
Hi @dev-prairedogtech,

Please follow thing node-gyp prerequisites: https://github.com/nodejs/node-gyp#installation

You are missing `make` which is included with `build-essential` I believe ...

**Comment by dev-prairedogtech** [comment]
I did sudo npm install make -g on C.H.I.P., but bleacon still doesn't install.  Looks like a compile error is occurring.
![img_0074 1](https://cloud.githubusercontent.com/assets/23701790/20674099/9ae0ede4-b555-11e6-9886-1c2c1fab59e4.JPG)
