### ISSUE TITLE
Not detecting any beacons if I run estimote/test.js

### ISSUE THREAD

**Issue by hashimK** [sandeepmistry/node-bleacon#71]
I've purchased the estimote location beacons and plan to detect them using a RaspberryPi. After carefully following your tutorial and steps, I cannot see any output when i run the estimote/test.js file. 
Also if i use ```
var Estimote = require('bleacon').Estimote;
Estimote.discoverAll(function (estimote) {
console.log(JSON.stringfy(estimote));
});
```I cannot find any beacons in my terminal.
The terminal window is just blank when i run either of the two codes.

**Comment by heypiotr** [comment]
The "Estimote" module is not compatible with the new Estimote Location and Proximity Beacons. Besides, that module was meant for configuring Estimote Beacons via _bleacon_. For simply detecting your beacons, use the iBeacon detection capabilities of _bleacon_, i.e., follow the instructions from README (:

**Comment by sandeepmistry** [comment]
Thanks @heypiotr!

Closing for now.
