### ISSUE TITLE
Beacon Detecting/Lost Region

### ISSUE THREAD

**Issue by arunseba** [sandeepmistry/node-bleacon#73]
@sandeepmistry Hi , Is it Possible to know when beacon is out of range?  Eg: we can detect a beacon enters into a region with "onDiscover" method and beacon parameters. likewise,can i get a when a beacon lost/ out of range?
Is there any method available to do that?

**Comment by sandeepmistry** [comment]
This is not supported with in the library, however you can extend the noble example to do something like this: https://github.com/sandeepmistry/noble/blob/master/examples/enter-exit.js

Please submit a pull request if you get something working ...
