### ISSUE TITLE
Failed to install on windows

### ISSUE THREAD

**Issue by cyclonmaster** [sandeepmistry/node-bleacon#74]
noble and bleano already installed successfully and working fine.

I try to npm install bleacon on windows 7. I get this error:

D:\estimote src>npm install bleacon

> bignum@0.11.0 install D:\estimote src\node_modules\bignum
> node-gyp configure build

D:\estimote src\node_modules\bignum>if not defined npm_config_node_gyp (node "C:
\Users\mkhairunns\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\n
ode_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "" configure
 build )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  bignum.cc
  win_delay_load_hook.cc
..\bignum.cc(413): warning C4244: '=': conversion from 'double' to 'uint64_t',
possible loss of data [D:\estimote src\node_modules\bignum\build\bignum.vcxproj
]
..\bignum.cc(385): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(413): warning C4996: 'v8::Value::ToNumber': was declared deprecate
d [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8166): note: see declar
  ation of 'v8::Value::ToNumber'
..\bignum.cc(461): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(474): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(488): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(502): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(520): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(538): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(557): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(576): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(585): warning C4996: 'v8::Value::ToUint32': was declared deprecate
d [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8196): note: see declar
  ation of 'v8::Value::ToUint32'
..\bignum.cc(589): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(598): warning C4996: 'v8::Value::ToUint32': was declared deprecate
d [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8196): note: see declar
  ation of 'v8::Value::ToUint32'
..\bignum.cc(602): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(614): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(626): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(640): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(659): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(674): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(691): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(707): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(720): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(727): warning C4996: 'v8::Value::ToUint32': was declared deprecate
d [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8196): note: see declar
  ation of 'v8::Value::ToUint32'
..\bignum.cc(734): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(744): warning C4996: 'v8::Value::ToUint32': was declared deprecate
d [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8196): note: see declar
  ation of 'v8::Value::ToUint32'
..\bignum.cc(753): warning C4996: 'v8::Value::ToUint32': was declared deprecate
d [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8196): note: see declar
  ation of 'v8::Value::ToUint32'
..\bignum.cc(861): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(893): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(928): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(952): warning C4996: 'v8::Value::ToUint32': was declared deprecate
d [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8196): note: see declar
  ation of 'v8::Value::ToUint32'
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay
32.lib' [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mkhairunns\AppData\Roaming\n
pm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mkhairunns\\A
ppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.j
s" "configure" "build"
gyp ERR! cwd D:\estimote src\node_modules\bignum
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modu
les\bleno\node_modules\xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-conne
ction@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":
"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modu
les\noble\node_modules\xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-conne
ction@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":
"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'D:\estimote src\package
.json'
npm WARN estimote src No description
npm WARN estimote src No repository field.
npm WARN estimote src No README data
npm WARN estimote src No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mkhairunns\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "bleacon"
npm ERR! node v6.9.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.11.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.11.0 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bignum
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\estimote src\npm-debug.log

D:\estimote src>node-gyp -v
v3.6.0

Please help

Thank you

**Comment by sandeepmistry** [comment]
@cyclonmaster does `npm install bignum` work by itself?

**Comment by cyclonmaster** [comment]
@sandeepmistry i tried npm install bignum, also failed. Any idea?

This is the full error log:

D:\estimote src>npm install bignum

> bignum@0.12.5 install D:\estimote src\node_modules\bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://rvagg-node.s3-us-west-2.amazon
aws.com/bignum/v0.12.5/bignum-v0.12.5-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@6.9.1
(node-v48 ABI) (falling back to source compile with node-gyp)

D:\estimote src\node_modules\bignum>if not defined npm_config_node_gyp (node "C:
\Users\mkhairunns\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\n
ode_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

D:\estimote src\node_modules\bignum>if not defined npm_config_node_gyp (node "C:
\Users\mkhairunns\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\n
ode_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build "--module=D:
\estimote src\node_modules\bignum\binding\bignum.node" --module_name=bignum "--m
odule_path=D:\estimote src\node_modules\bignum\binding" --python=C:\Users\mkhair
unns\.windows-build-tools\python27\python.exe --msvs_version=2015 )  else (node
"" configure --fallback-to-build "--module=D:\estimote src\node_modules\bignum\b
inding\bignum.node" --module_name=bignum "--module_path=D:\estimote src\node_mod
ules\bignum\binding" --python=C:\Users\mkhairunns\.windows-build-tools\python27\
python.exe --msvs_version=2015 )

D:\estimote src\node_modules\bignum>if not defined npm_config_node_gyp (node "C:
\Users\mkhairunns\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\n
ode_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build "--module=D:\est
imote src\node_modules\bignum\binding\bignum.node" --module_name=bignum "--modul
e_path=D:\estimote src\node_modules\bignum\binding" )  else (node "" build --fal
lback-to-build "--module=D:\estimote src\node_modules\bignum\binding\bignum.node
" --module_name=bignum "--module_path=D:\estimote src\node_modules\bignum\bindin
g" )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  bignum.cc
  win_delay_load_hook.cc
..\bignum.cc(413): warning C4244: '=': conversion from 'double' to 'uint64_t',
possible loss of data [D:\estimote src\node_modules\bignum\build\bignum.vcxproj
]
..\bignum.cc(385): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(413): warning C4996: 'v8::Value::ToNumber': was declared deprecate
d [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8166): note: see declar
  ation of 'v8::Value::ToNumber'
..\bignum.cc(461): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(474): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(488): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(502): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(520): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(538): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(557): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(576): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(585): warning C4996: 'v8::Value::ToUint32': was declared deprecate
d [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8196): note: see declar
  ation of 'v8::Value::ToUint32'
..\bignum.cc(589): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(598): warning C4996: 'v8::Value::ToUint32': was declared deprecate
d [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8196): note: see declar
  ation of 'v8::Value::ToUint32'
..\bignum.cc(602): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(614): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(626): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(640): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(659): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(674): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(691): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(707): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(720): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(727): warning C4996: 'v8::Value::ToUint32': was declared deprecate
d [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8196): note: see declar
  ation of 'v8::Value::ToUint32'
..\bignum.cc(734): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(744): warning C4996: 'v8::Value::ToUint32': was declared deprecate
d [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8196): note: see declar
  ation of 'v8::Value::ToUint32'
..\bignum.cc(753): warning C4996: 'v8::Value::ToUint32': was declared deprecate
d [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8196): note: see declar
  ation of 'v8::Value::ToUint32'
..\bignum.cc(810): warning C4267: '=': conversion from 'size_t' to 'int', possi
ble loss of data [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(825): warning C4267: '=': conversion from 'size_t' to 'int', possi
ble loss of data [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(994): warning C4996: 'v8::Function::NewInstance': was declared dep
recated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(1026): warning C4996: 'v8::Function::NewInstance': was declared de
precated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(1061): warning C4996: 'v8::Function::NewInstance': was declared de
precated [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(3270): note: see declar
  ation of 'v8::Function::NewInstance'
..\bignum.cc(1085): warning C4996: 'v8::Value::ToUint32': was declared deprecat
ed [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
  c:\users\mkhairunns\.node-gyp\6.9.1\include\node\v8.h(8196): note: see declar
  ation of 'v8::Value::ToUint32'
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay
32.lib' [D:\estimote src\node_modules\bignum\build\bignum.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mkhairunns\AppData\Roaming\n
pm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mkhairunns\\A
ppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.j
s" "build" "--fallback-to-build" "--module=D:\\estimote src\\node_modules\\bignu
m\\binding\\bignum.node" "--module_name=bignum" "--module_path=D:\\estimote src\
\node_modules\\bignum\\binding"
gyp ERR! cwd D:\estimote src\node_modules\bignum
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-
to-build --module=D:\estimote src\node_modules\bignum\binding\bignum.node --modu
le_name=bignum --module_path=D:\estimote src\node_modules\bignum\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\estimote src\node_mo
dules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\estimote sr
c\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build
"
node-pre-gyp ERR! cwd D:\estimote src\node_modules\bignum
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\estimote s
rc\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=D:
\estimote src\node_modules\bignum\binding' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modu
les\bleno\node_modules\xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-conne
ction@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":
"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modu
les\noble\node_modules\xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-conne
ction@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":
"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'D:\estimote src\package
.json'
npm WARN estimote src No description
npm WARN estimote src No repository field.
npm WARN estimote src No README data
npm WARN estimote src No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mkhairunns\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "bignum"
npm ERR! node v6.9.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bignum
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\estimote src\npm-debug.log

**Comment by cyclonmaster** [comment]
Finally I solved the problem. Seem like the OpenSSL lib location for Windows is different than linux.

I reinstalled OpenSSL version 1.0.2, then copy libeay32.dll from bin & libeay32.lib(google) into C:\OpenSSL-Win64\lib

Then npm install bignum

After that npm install bleacon

All working fine now.

**Comment by sandeepmistry** [comment]
Closing as resolved. Thanks for the update.
