### ISSUE TITLE
Bleacon not working on startup

### ISSUE THREAD

**Issue by pmuno007** [sandeepmistry/node-bleacon#76]
I want to execute a bleacon script I made on startup. I created a bash script with this command on it:

node /path/to/file/myScript.js

This works when I run it manually. When I add it to crontab, the following happens.
The script starts (I have logging enabled so I can see that it runs), it goes through the startScanning() function, but the logic inside the on('discover'...} event is never hit.

I also tried putting the bash script on the init.d and do the update-rc.d myscript.js defaults route but the same issue described before happens.

Again, if I run the bash script manually, it calls my script and everything works. What could be the issue? How can I execute my bleacon script automatically on startup?

Note: I have tested putting other node scripts (not using bleacon) on this bash script and they are executed successfully.

**Comment by migmad** [comment]
I was having the same issue as you today. My "fix" was to include a sleep command before launching node. It's not ideal and I still don't know why this happens - though I suspect it has to do with an inconsistent, timing-sensitive issue with the bluetooth demon or something - but it works.

**Comment by sandeepmistry** [comment]
@pmuno007 @migmad I would make sure the script is started after bluetoothd is started.
