### ISSUE TITLE
startScanning Not Detecting Beacons

### ISSUE THREAD

**Issue by AndrewReitz** [sandeepmistry/node-bleacon#9]
I have 3 iBeacons and running startScanning doesn't seem to detect any of them. I am running Fedora 20 with Node v0.10.28

**Comment by gerdavax** [comment]
Hello.
I'm experiencing something similar with bleacon.startScanning(). All the noble scripts work as expected, including the advertisement-discovery.js mentioned in the previous comments. However, the test.js and the following code fragment do not produce any output:

Bleacon = require('bleacon');
Bleacon.on('discover', function(bleacon) {
  console.log('bleacon found: ' + JSON.stringify(bleacon));
});
Bleacon.startScanning();

Native lescan and the noble scripts work correctly. What's wrong with Bleacon.startScanning?
Thank you.

**Comment by sandeepmistry** [comment]
@gerdavax please create a new issue with debug output? ```DEBUG=* node <file>.js```
